version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "wb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
 
    ports:
      - "5432:5432"

  nats-streaming:
    # command:
    # - nats-streaming
    image: nats-streaming
    container_name: nats-streaming
    ports:
    - 4222:4222
